name          'bashtoni-scl'
version       '0.0.1'
source        'UNKNOWN'
author        'bashtoni'
license       'Apache License, Version 2.0'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib', '>= 4.1.0'
